<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0-windows</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<DisableRuntimeMarshalling>true</DisableRuntimeMarshalling>
		<CsWin32RunAsBuildTask>true</CsWin32RunAsBuildTask>
		
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<Title>Maple.XScheduler.WinMsg</Title>
		<RepositoryUrl>https://github.com/blackmaple/Maple.XScheduler</RepositoryUrl>
		<PackageLicenseFile>LICENSE</PackageLicenseFile>
		<PackageRequireLicenseAcceptance>False</PackageRequireLicenseAcceptance>
		<Description>dotNet Maple.XScheduler.WinMsg</Description>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageTags>hook;c#;dotnet;AOT</PackageTags>
		<Version>0.26.0524.01-rc</Version>
	</PropertyGroup>
	<ItemGroup>
		<None Include="..\LICENSE" Link="LICENSE">
			<PackagePath>\</PackagePath>
			<Pack>True</Pack>
		</None>
		<None Include="..\README.md" Link="README.md">
			<PackagePath>\</PackagePath>
			<Pack>True</Pack>
		</None>
	</ItemGroup>




	<ItemGroup>
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.3.0" />
		<PackageReference Include="Microsoft.Windows.CsWin32" Version="0.3.275">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.8" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Maple.Hook.WinMsg\Maple.Hook.WinMsg.csproj" />
		<ProjectReference Include="..\Maple.XScheduler\Maple.XScheduler.csproj" />
	</ItemGroup>

</Project>
